# -*- coding: utf-8 -*-
"""MLAssignment1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S1gRAQfLlROEg_hdhcxznAouwUd949sA
"""

#10 Program to convert a given string to uppercase
user_string = input("Enter a string: ")
uppercase_string = user_string.upper()
print("The uppercase version of the string is:", uppercase_string)

# 11 Print nth fibonnaci
a=0
b=1
n=int(input("Enter the no of fibonnaci numbers you want to be generated:"))
for i in range(n):
    print(a)
    c=a+b
    a=b
    b=c

#12 Program to calculate the sum of the digits of a given number
def sum_of_digits(number):
  if(number==0):
      return 0

  digit=number%10
  number=number//10;
  sum=digit+sum_of_digits(number)
  return sum


number = int(input("Enter a number: "))
sum_digits = sum_of_digits(number)
print(f"The sum of the digits of {number} is {sum_digits}")

#13 Program to ask the user for their birth year and calculate their age
current_year = 2024
birth_year = int(input("Enter your birth year: "))
age = current_year - birth_year
print(f"You are {age} years old.")