# -*- coding: utf-8 -*-
"""MLAssignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkLTdMJwNNMhVY9_DN4kmxqo0R8iVKgZ
"""

#1 Program to take two numbers as input and print their sum
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
sum = num1 + num2
print("The sum of", num1, "and", num2,"is", sum)

#2 Program to check whether a given number is even or odd
number = int(input("Enter a number: "))
if (number % 2 == 0):
    print(number,"is even")
else:
    print(number,"is odd")

#3 Program to calculate the factorial of a given number
def factorial(n):
    if (n == 0 or n == 1):
        return 1
    else:
        return n * factorial(n - 1)

number = int(input("Enter a number to find its factorial: "))
result = factorial(number)
print("The factorial of", number, "is", result)

#4 Program to ask the user for their name and print a greeting message
name = input("Enter your name: ")
print("Hello",name,'!')

#5 Program to take a string input from the user and write it to a text file
user_input = input("Enter a string: ")
with open("textfile.txt", "w") as file:
    file.write(user_input)
print("The string has been written to textfile.txt")

#6 Program to read the content of a text file and print it to the console
try:
    with open("textfile.txt", "r") as file:
        content = file.read()
        print("The content of the file is:")
        print(content)
except FileNotFoundError:
    print("The file does not exist.")

#7 Program to take a string as input and return its length
user_string = input("Enter a string: ")
length = len(user_string)
print("The length of the string is", length)

#8 Program to concatenate two strings and return the result
string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")
result = string1 + string2
print("The concatenated string is:", result)

#9 Program to check if a substring is present in a given string using find()
main_string = input("Enter the main string: ")
substring = input("Enter the substring: ")
if main_string.find(substring) != -1:
    print(f"The substring '{substring}' is present in the main string.")
else:
    print(f"The substring '{substring}' is not present in the main string.")

