# -*- coding: utf-8 -*-
"""MLAssignment1.2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SaPP4-emWMve37ypJ9vn8nTDInuLR9l
"""

#14 Program to read multiple lines of input from the user until they enter an empty line, then print all the lines
lines = []
print("Enter multiple lines of text:")
while True:
    line = input()
    if line == "":
        break
    lines.append(line)

print("\nYou entered:")
for line in lines:
    print(line)

import csv

#15 Program to read data from a CSV file and print it to the console
file_path = input("Enter the path to the CSV file: ")

try:
    with open(file_path, newline='') as csvfile:
        csvreader = csv.reader(csvfile)
        for row in csvreader:
            print(', '.join(row))
except FileNotFoundError:
    print("The file does not exist.")

#16 Program to count the frequency of each character in a string
def count_character_frequency(string):
    frequency = {}
    for char in string:
        if char in frequency:
            frequency[char] += 1
        else:
            frequency[char] = 1
    return frequency

user_string = input("Enter a string: ")
frequency = count_character_frequency(user_string)
print("Character frequency:")
for char, count in frequency.items():
    print(f"'{char}': {count}")

#17 Program to convert a given string to title case
user_string = input("Enter a string: ")
title_case_string = user_string.title()
print(f"The title case version of the string is: {title_case_string}")

#18 Program to check if two strings are anagrams
def are_anagrams(str1, str2):
    return sorted(str1) == sorted(str2)

str1 = input("Enter the first string: ")
str2 = input("Enter the second string: ")

if are_anagrams(str1, str2):
    print(f"'{str1}' and '{str2}' are anagrams.")
else:
    print(f"'{str1}' and '{str2}' are not anagrams.")

#19 program that removes all punctuation from a given string
import string
user_input = input("Enter a string: ")
for punctuation in string.punctuation:
    user_input = user_input.replace(punctuation, "")
print("String without punctuation:", user_input)

#20 program that takes a list of numbers and returns their sum
numbers = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
print("Sum of the list is:", sum(numbers))

#21 program that counts the occurrences of a specific element in a list
lst = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
element = int(input("Enter the element to count: "))
print(f"{element} occurs {lst.count(element)} times.")

#22 program that returns the minimum and maximum values in a list of numbers
lst = list(map(int, input("Enter a list of numbers separated by spaces: ").split()))
minimum, maximum = min(lst), max(lst)
print(f"Minimum value is {minimum}, Maximum value is {maximum}.")45

#23 program that converts temperature from Celsius to Fahrenheit and vice versa based on user input
f_to_c=1
c_to_f=2
choice=int(input("enter 1 for ^f to ^c conversion or enter 2 for ^c to ^f conversion:"))
if choice==1:
  f=float(input('Enter temperature in Fahrenheit:'))
  con1=(f-32)/1.8
  print("The temperature is",con1,"degree Celsius")
elif choice==2:
  c=float(input('Enter temperature in Celsius:'))
  con2=(c*1.8)+32
  print("The temperature is",con2,"degree Fahrenheit")

#24 program that acts as a simple calculator
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operator = input("Enter an operator (+, -, *, /): ")
if operator == '+':
    result = num1 + num2
elif operator == '-':
    result = num1 - num2
elif operator == '*':
    result = num1 * num2
elif operator == '/':
    result = num1 / num2
else:
    result = "Invalid operator"
print("The result is: ", result)

#25 program that copies the contents of one text file to another
src = input("Enter the source file path: ")
dest = input("Enter the destination file path: ")
with open(src, "r") as source_file:
    content = source_file.read()
with open(dest, "w") as destination_file:
    destination_file.write(content)

#26 program that checks if a string starts with a given prefix or ends with a given suffix
string = input("Enter a string: ")
prefix = input("Enter the prefix to check: ")
suffix = input("Enter the suffix to check: ")
starts_with = string.startswith(prefix)
ends_with = string.endswith(suffix)
print(f"String starts with {prefix}: {starts_with}")
print(f"String ends with {suffix}: {ends_with}")

#27 program that converts a string into a list of its characters
user_input = input("Enter a string: ")
print(list(user_input))